# Use an official Python runtime as base image
FROM python:3.7

# Set the working directory in the container
WORKDIR /C:\Users\jayu\Desktop\jayashri

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run emojify_project_through_graph.py when the container launches
CMD ["python", "emojify_project_through_graph.py"]


 